auto:       true
server:     true
permalink:  /writing/:year/:month/:day/:title
baseurl:    /
name: Ryan Rushing, designer
description: Ryan is a designer living in the Dallas-area. Sometimes he writes.
url: http://ryan-rushing.comls
